version: 2

aliases:
  - &docker-node-11
    - image: circleci/node:11.10.1

jobs:
  build:
    docker: *docker-node-11
    steps:
      - checkout
      - run: echo 'starting ci'

  lint:
    docker: *docker-node-11
    steps:
      - checkout
      - run: npm install
      - run: npm run lint

workflows:
  version: 2
  build_lint_test:
    jobs:
      - build
      - lint
